# Docker
# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
  branches:
   include:
   - main
  paths:
    include:
      - src/ApiGateWays/OcelotApiGw

resources:
- repo: self



variables:
  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: 'AzureACR'
  imageRepository: 'task.gateway'
  containerRegistry: 'tasklist.azurecr.io'
  dockerfilePath: '$(Build.SourcesDirectory)/src/ApiGateWays/OcelotApiGw/Dockerfile'
  dockerBuildContext: '$(Build.SourcesDirectory)/src'
  tag: '$(Build.BuildId)'

  # Agent VM image name
  vmImageName: 'ubuntu-latest'

stages:
- stage: Build
  displayName: Build and push stage
  jobs:
  - job: Build
    displayName: Build
    pool: 'Default'
    steps:
    - task: Docker@2
      displayName: Build and push an image to container registry
      inputs:
        command: buildAndPush
        repository: $(imageRepository)
        dockerfile: $(dockerfilePath)
        buildContext: $(dockerBuildContext)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: $(tag)
    - task: AzureCLI@2
      inputs:
        azureSubscription: 'Azure-RM'
        scriptType: 'ps'
        scriptLocation: inlineScript
        inlineScript: kubectl set image deployment/task-gateway task-gateway=$(imageRepository):$(tag)
        addSpnToEnvironment: true
    
      
