# Docker
# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
  branches:
   include:
   - main
  paths:
    include:
      - src/ApiGateWays/OcelotApiGw

resources:
- repo: self

variables:
  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: '9437b7ad-6f35-4620-abec-126da1e70747'
  imageRepository: 'jghalaeitasklist'
  containerRegistry: 'tasklist.azurecr.io'
  dockerfilePath: '$(Build.SourcesDirectory)/src/ApiGateWays/OcelotApiGw/Dockerfile'
  tag: 'task.gateway:$(Build.BuildId)'

  # Agent VM image name
  vmImageName: 'ubuntu-latest'

stages:
- stage: Build
  displayName: Build and push stage
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: Docker@2
      displayName: Build and push an image to container registry
      inputs:
        command: buildAndPush
        repository: $(imageRepository)
        dockerfile: $(dockerfilePath)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(tag)
    - task: AzureCLI@2
      inputs:
        azureSubscription: ''
        scriptType: 'bash'
        scriptLocation: inlineScript
        inlineScript: kubectl set image deployment/task-gateway task.gateway=$(containerRegistry)/$(tag)
        addSpnToEnvironment: true
    
      
