apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-api
  labels:
    app: task-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: task-api
  template:
    metadata:
      labels:
        app: task-api
    spec:
      imagePullSecrets:
        - name: acr-secret
      containers:
        - name: task-api
          image: tasklist.azurecr.io/task.api:latest
          ports:
            - containerPort: 5002
          livenessProbe:
            httpGet:
              path: /health
              port: 5002
          readinessProbe:
            httpGet:
              path: /health
              port: 5002
          resources:
            limits:
              cpu: "500m"
              memory: "1Gi"
            requests:
              cpu: "250m"
              memory: "512Mi"
          env:
            - name: ASPNETCORE_ENVIRONMENT
              valueFrom:
                configMapKeyRef:
                  name: tasklist-config
                  key: ASPNETCORE_ENVIRONMENT
            - name: "TaskDb__Server"
              valueFrom:
                configMapKeyRef:
                  name: tasklist-config
                  key: TaskDb_Server

            - name: "TaskDb__Port"
              valueFrom:
                configMapKeyRef:
                  name: tasklist-config
                  key: TaskDb_Port

            - name: "TaskDb__Database"
              valueFrom:
                configMapKeyRef:
                  name: tasklist-config
                  key: TaskDb_Database
            - name: "TaskDb__UserId"
              valueFrom:
                secretKeyRef:
                  name: mysecret
                  key: TaskDb_username
            - name: "TaskDb__Password"
              valueFrom:
                secretKeyRef:
                  name: mysecret
                  key: TaskDb_password

            - name: "Jwt__Key"
              valueFrom:
                secretKeyRef:
                  name: mysecret
                  key: JWT_Secret
            - name: "Jwt__Issuer"
              valueFrom:
                configMapKeyRef:
                  name: tasklist-config
                  key: JWT_Issuer
            - name: "Jwt__Audience"
              valueFrom:
                configMapKeyRef:
                  name: tasklist-config
                  key: JWT_Audience
