version: "3.4"

services:
  TaskDb:
    container_name: TaskDb
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin1234
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@aspnetrun.com
      - PGADMIN_DEFAULT_PASSWORD=admin1234
    restart: always
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/root/.pgadmin

  user.api:
    container_name: user.api
    environment:
      - "ASPNETCORE_ENVIRONMENT=Development"
      - "ConnectionStrings:UsersDb=Server=TaskDb;Port=5432;Database=UsersDb;User Id=admin;Password=admin1234;"
    ports:
      - "8001:5001"

    restart: always
    depends_on:
      - TaskDb

  task.api:
    container_name: task.api
    environment:
      - "ASPNETCORE_ENVIRONMENT=Development"
      - "ConnectionStrings:TaskDb=Server=TaskDb;Port=5432;Database=TaskDb;User Id=admin;Password=admin1234;"
    ports:
      - "8002:5002"

    restart: always
    depends_on:
      - TaskDb

  task.gateway:
    container_name: task.gateway
    environment:
      - "ASPNETCORE_ENVIRONMENT=Development"
    ports:
      - "8000:5000"
    restart: always
    depends_on:
      - user.api
      - task.api

  tasklist.app:
    container_name: tasklist.app
    ports:
      - "80:3000"
    restart: always
    depends_on:
      - task.gateway
