version: "3.4"

services:
  TaskDb:
    container_name: TaskDb
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin1234
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@aspnetrun.com
      - PGADMIN_DEFAULT_PASSWORD=admin1234
    restart: always
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/root/.pgadmin

  elasticsearch:
    container_name: elasticsearch
    ports:
      - 9200:9200
    restart: always
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data

  kibana:
    container_name: kibana
    ports:
      - 5601:5601
    restart: always
    environment:
      - ELASTICSEARCH_URL=http://localhost:9200
    depends_on:
      - elasticsearch
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.9.9-management-alpine
    ports:
      - 5672:5672
      - 15672:15672
    restart: always

  user.api:
    container_name: user.api
    environment:
      - "ASPNETCORE_ENVIRONMENT=Development"
      - "UsersDb:Server=TaskDb"
      - "UsersDb:Port=5432"
      - "UsersDb:Database=UsersDb"
      - "UsersDb:UserId=admin"
      - "UsersDb:Password=admin1234"
      - "ElasticConfiguration:Uri=http://elasticsearch:9200"
    ports:
      - "5004:80"

    restart: always
    depends_on:
      - TaskDb

  task.api:
    container_name: task.api
    environment:
      - "ASPNETCORE_ENVIRONMENT=Development"
      - "TaskDb:Server=TaskDb"
      - "TaskDb:Port=5432"
      - "TaskDb:Database=TaskDb"
      - "TaskDb:UserId=admin"
      - "TaskDb:Password=admin1234"
      - "ElasticConfiguration:Uri=http://elasticsearch:9200"
    ports:
      - "5003:80"

    restart: always
    depends_on:
      - TaskDb

  task.gateway:
    container_name: task.gateway
    environment:
      - "ASPNETCORE_ENVIRONMENT=Development"
      - "ElasticConfiguration:Uri=http://elasticsearch:9200"
    ports:
      - "5000:80"
    restart: always
    depends_on:
      - user.api
      - task.api

  tasklist.app:
    container_name: tasklist.app
    environment:
      - "REACT_APP_BACKEND_URL=http://localhost:8000"
    ports:
      - "3000:3000"
    restart: always
    depends_on:
      - task.gateway
